// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUG5IgVL99d__XSh7bREQ7Gt1i_X58f-c',
    appId: '1:149468488682:web:cee4ad1faa668d3098c893',
    messagingSenderId: '149468488682',
    projectId: 'smwallets-f95f4',
    authDomain: 'smwallets-f95f4.firebaseapp.com',
    storageBucket: 'smwallets-f95f4.firebasestorage.app',
    measurementId: 'G-YX6TZ2E0Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQXBQx8_k15U-7M5X7TSTJZgWNWyRFfwE',
    appId: '1:149468488682:android:60bcc1431b4d333098c893',
    messagingSenderId: '149468488682',
    projectId: 'smwallets-f95f4',
    storageBucket: 'smwallets-f95f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrPiepiB2D4iCBw6qR3hB3tpkLznmpY4g',
    appId: '1:149468488682:ios:7b0156f009773e8e98c893',
    messagingSenderId: '149468488682',
    projectId: 'smwallets-f95f4',
    storageBucket: 'smwallets-f95f4.firebasestorage.app',
    iosBundleId: 'com.example.smWallets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrPiepiB2D4iCBw6qR3hB3tpkLznmpY4g',
    appId: '1:149468488682:ios:7b0156f009773e8e98c893',
    messagingSenderId: '149468488682',
    projectId: 'smwallets-f95f4',
    storageBucket: 'smwallets-f95f4.firebasestorage.app',
    iosBundleId: 'com.example.smWallets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUG5IgVL99d__XSh7bREQ7Gt1i_X58f-c',
    appId: '1:149468488682:web:72fbb47ac4ad9c5c98c893',
    messagingSenderId: '149468488682',
    projectId: 'smwallets-f95f4',
    authDomain: 'smwallets-f95f4.firebaseapp.com',
    storageBucket: 'smwallets-f95f4.firebasestorage.app',
    measurementId: 'G-S9Z9DX6596',
  );

}